[CSharp-RichCards] Update to Microsoft.Bot.Builder v3.4.0 and add references to new emulator in README.md
southworks/BotBuilder-Samples pull request #12
Opened 2017-01-03 14:18 UTC by ejadib

TBD if we need to add the new cards: AnimationCard, VideoCard and AudioCard

2017-01-03 16:36 UTC, pcostantini commented on CSharp/cards-RichCards/README.md
At L108 it reads:
> For a complete authentication flow sample take a look **to** the [AuthBot](https://github.com/matvelloso/authbot).

Shouldn't it read as:

> For a complete authentication flow sample take a look **at** the [AuthBot](https://github.com/matvelloso/authbot).

2017-01-03 16:37 UTC, pcostantini approved these changes
There may by a grammar error in the Readme file where it links to the AuthBot.
Also, the AuthBot was moved to https://github.com/MicrosoftDX/AuthBot

2017-01-03 16:39 UTC, pcostantini requested changes
Please check grammar issue where it links to Authbot,
Also, AuthBot was moved to 
https://github.com/MicrosoftDX/AuthBot

2017-01-03 17:49 UTC, ejadib commented on CSharp/cards-RichCards/README.md
Done

2017-01-03 18:50 UTC, pcostantini approved these changes

2017-01-06 13:03 UTC, pcostantini commented on CSharp/cards-RichCards/CardsDialog.cs
> +            var currentUrl = HttpContext.Current.Request.Url;
Unused var

2017-01-06 13:03 UTC, pcostantini commented on CSharp/cards-RichCards/CardsDialog.cs
> +            var currentUrl = HttpContext.Current.Request.Url;
Unused var

2017-01-06 13:39 UTC, ejadib commented on CSharp/cards-RichCards/CardsDialog.cs
> +            var currentUrl = HttpContext.Current.Request.Url;
Removed

2017-01-06 13:39 UTC, ejadib commented on CSharp/cards-RichCards/CardsDialog.cs
> +            var currentUrl = HttpContext.Current.Request.Url;
Removed

2017-01-09 15:51 UTC, pcostantini approved these changes

2017-01-09 16:36 UTC, merged