[netcore][12.nlp-with-luis] Minor text style tweaks
southworks/BotBuilder-Samples pull request #129
Opened 2018-10-18 18:52 UTC by VictorGrycuk

## Proposed Changes
Minor style tweaks in readme and code for sample # 12.
Additionally modified the steps to obtain LUIS keys and infomation.

## Testing
Code behavior was not modified.

2018-10-19 16:37 UTC, joseques approved these changes
:shipit: 👍

2018-10-24 19:13 UTC, dfavretto requested changes

2018-10-24 19:13 UTC, dfavretto commented on samples/csharp_dotnetcore/12.nlp-with-luis/README.md
>  # Deploy this bot to Azure
Update this section with the corrections implemented in other samples, like in [sample 08](https://github.com/Microsoft/BotBuilder-Samples/blame/5be0364be8614b42469a630e8c7343c96364253e/samples/csharp_dotnetcore/06.using-cards/readme.md#L34)

2018-10-25 16:22 UTC, dfavretto commented
Closed due to Microsoft#771

2018-10-25 16:22 UTC, closed without merging