[01.console-echo] Unify structure of 'readme.md'
southworks/BotBuilder-Samples pull request #137
Opened 2018-10-22 19:51 UTC by VictorGrycuk

## Proposed Changes
Unify the structure of `readme.md` across the differente languages in sample **01.console-echo**.

## Testing
The behaviour of the code was not modified.

2018-10-22 19:53 UTC, joseques requested changes

2018-10-22 19:53 UTC, joseques commented on samples/javascript_nodejs/01.console-echo/README.md
> +- In a terminal, navigate to samples/javascript_nodejs/01.console-echo
Please change the paths in `code style`

2018-10-22 20:17 UTC, joseques approved these changes

2018-11-20 13:52 UTC, VictorGrycuk commented
No longer needed

2018-11-20 13:52 UTC, closed without merging