[02.echo-with-counter] Unify structure of 'readme.md'
southworks/BotBuilder-Samples pull request #138
Opened 2018-10-22 19:54 UTC by VictorGrycuk

## Proposed Changes
Unify the structure of `readme.md` across the differente languages in sample **02.echo-with-counter**.

## Testing
The behaviour of the code was not modified.

2018-10-22 19:55 UTC, joseques requested changes

2018-10-22 19:55 UTC, joseques commented on samples/csharp_dotnetcore/02.echo-with-counter/README.md
> +- **Optional**: Update the `appsettings.json` file under `botbuilder-samples/samples/csharp_dotnetcore/02.echo-with-counter` with your botFileSecret.  For Azure Bot Service bots, you can find the bot
For consistency, style the botFileSecret to `code style` used in most READMEs

2018-10-23 12:21 UTC, joseques approved these changes

2018-10-23 18:20 UTC, joseques approved these changes
👀 👍

2018-11-20 13:52 UTC, VictorGrycuk commented
No longer needed

2018-11-20 13:52 UTC, closed without merging