Fix #772 - Add appId, appSecret to msbot command and instructions to obtain them
southworks/BotBuilder-Samples pull request #159
Opened 2018-10-31 18:54 UTC by joseques

Fixes Microsoft#722
## Proposed Changes
- `--appId` and `--appSecret` parameters to all `msbot clone services` commands found in the READMEs
- Add instructions to obtain the `appId` and `appSecret` at the [Application Registration Portal](https://apps.dev.microsoft.com/)

2018-10-31 20:32 UTC, VictorGrycuk approved these changes
🚢 it

2018-11-02 17:00 UTC, dfavretto requested changes

2018-11-02 17:00 UTC, dfavretto commented on samples/csharp_dotnetcore/12.nlp-with-luis/README.md
> +
```suggestion
```

2018-11-20 13:45 UTC, dfavretto approved these changes

2018-11-20 13:45 UTC, dfavretto commented
Closed due to Microsoft#824

2018-11-20 13:45 UTC, closed without merging