[NodeJS][25.bot-logging] - Added 'appId' and 'appSecret' to msbot command and instructions to obtain them
southworks/BotBuilder-Samples pull request #162
Opened 2018-11-08 15:11 UTC by GasparAcevedoZainSouthworks

## Proposed Changes
- Added 'appId' and 'appSecret' to msbot command and instructions to obtain them
- Updated botbuilder version from 4.0.6 to 4.1.5 to solve vulnerabilities issues
- Updated README.md file to match with template
- Fixed minor typos

2018-11-08 15:44 UTC, joseques requested changes

2018-11-08 15:44 UTC, joseques commented on samples/javascript_nodejs/25.logger-bot/README.md
> +- In a terminal, navigate to samples/javascript_nodejs/25.logger-bot
Please use `code style` when mentioning paths, files or variable names.

2018-11-08 15:44 UTC, joseques commented on samples/javascript_nodejs/25.logger-bot/README.md
> +- [Optional] Update the .env file under samples/javascript_nodejs/25.logger-bot with your botFileSecret For Azure Bot Service bots, you can find the botFileSecret under application settings.
Please use code style when mentioning paths, files or variable names.

2018-11-08 15:44 UTC, joseques commented on samples/javascript_nodejs/25.logger-bot/README.md
> +To install all Bot Builder tools, follow these [instructions][11].
For consistency, can you change the instructions as we have it in [other samples](https://github.com/southworkscom/BotBuilder-Samples/commit/99f4189f5330c9d61dc76a2effaa3cc41d97d0f7#diff-671f2784abcf5c38d62133d9f710dbaaR41)?

2018-11-08 15:51 UTC, VictorGrycuk approved these changes
Fix @joseques requests and 🚢 it

2018-11-08 22:51 UTC, dfavretto requested changes
Along with the inline requested changes, I suggest to re-write the PR using Present conjugations instead of Past conjugations, because in Past time, the one reading the PR may interpret the changes are already implemented, but the idea is to make the other person understand that the PR is implementing these changes in the moment they read it. 

Also, try making the title more generic, not going to the specific change in the `msbot clone services` command, it should be something more like `Fix typos and improve Readme structure and content`

2018-11-08 22:51 UTC, dfavretto commented on samples/javascript_nodejs/25.logger-bot/README.md
> +msbot clone services -f deploymentScripts/msbotClone -n <BOT-NAME> -l <Azure-location> --subscriptionId <Azure-subscription-id> --appID <App-Id> --appSecret <App-Secret>
Be careful here, the `--appID` should be `--appId`
```suggestion
msbot clone services -f deploymentScripts/msbotClone -n <BOT-NAME> -l <Azure-location> --subscriptionId <Azure-subscription-id> --appId <App-Id> --appSecret <App-Secret>
```

2018-11-08 22:51 UTC, dfavretto commented on samples/javascript_nodejs/25.logger-bot/README.md
> +[11]: https://github.com/southworkscom/BotBuilder-Samples/blob/master/Installing_CLI_tools.md#install-cli-tools
As you can see [here](https://github.com/Microsoft/BotBuilder-Samples/blame/master/samples/javascript_nodejs/06.using-cards/README.md#L47) we tend to use the relative path to the `Install CLI Tools` file, taking advantage it's in the root folder of the repo, and the user has to clone the entire repo to try the sample.
```suggestion
[11]: ../../../Installing_CLI_tools.md
```

2018-11-09 14:08 UTC, dfavretto approved these changes

2018-11-09 14:08 UTC, joseques approved these changes

2018-11-20 13:44 UTC, dfavretto commented
Closed due to Microsoft#870

2018-11-20 13:44 UTC, closed without merging