[botkit] Add Facebook Adapter Bot sample
southworks/BotBuilder-Samples pull request #197
Opened 2019-10-23 20:39 UTC by LCarbonellRod

### Description

- Add new sample. Echo bot to test the Facebook Adapter.

- A README file is added with the steps to connect the bot with Facebook Api to use the bot.

_**Note**: This PR will fail until the Facebook Adapter nuget package gets published._

2019-10-23 20:48 UTC, ceciliaavila requested changes

2019-10-23 20:48 UTC, ceciliaavila commented on samples/csharp_dotnetcore/55.facebook-adapter/README.md
> +﻿# EchoBot using Facebook Adapter
Please change the title to match the rest of the samples

2019-10-23 20:48 UTC, ceciliaavila commented on samples/csharp_dotnetcore/55.facebook-adapter/README.md
> +﻿# EchoBot using Facebook Adapter
Please change the title to match with the rest of the adapters.

2019-10-23 20:48 UTC, ceciliaavila commented on samples/csharp_dotnetcore/55.facebook-adapter/README.md
> +- Create a Facebook Account for Developers (https://developers.facebook.com/).
These steps should have numbers, you'll need them to indicate how to set the tokens in appsettings.json

2019-10-23 20:48 UTC, ceciliaavila commented on samples/csharp_dotnetcore/55.facebook-adapter/wwwroot/default.htm
> +    <title>Microsoft.Bot.Builder.Facebook.Sample</title>
Change the title here.

2019-10-24 12:08 UTC, ceciliaavila approved these changes

2019-10-24 12:46 UTC, matiasroldan6 approved these changes

2023-07-07 12:57 UTC, closed without merging