[#3499] Migrate JS samples and generators to Cloud Adapter - samples/skills
southworks/BotBuilder-Samples pull request #324
Opened 2021-10-06 17:46 UTC by sw-joelmut

Addresses # 3499

## Description
This PR updates the samples `80.skills-simple-bot-to-bot` and `81.skills-skilldialog` to use **_Cloud Adapter_** instead of **_BotFrameworkAdapter_**. 

### Detailed Changes
Updated the following bots:
- 80.skills-simple-bot-to-bot/simple-root-bot
- 80.skills-simple-bot-to-bot/echo-skill-bot
- 81.skills-skilldialog/dialogRootBot
- 81.skills-skilldialog/dialogSkillBot

Removed `allowedCallersClaimsValidator` and `skillConversationIdFactory` to use the ones from the SDK.

## Testing
The following image shows the Bot-to-Bot and SkillDialog skills samples.
![image](https://user-images.githubusercontent.com/62260472/136254788-d64d678a-0375-4553-88d2-c971b3405d82.png)

2021-10-06 20:53 UTC, ceciliaavila requested changes

2021-10-06 20:53 UTC, ceciliaavila commented on samples/javascript_nodejs/80.skills-simple-bot-to-bot/simple-root-bot/index.js
> +const conversationIdFactory = new SkillConversationIdFactory(new MemoryStorage());
Should we use `memoryStorage` const instead?

2021-10-06 20:53 UTC, ceciliaavila commented on samples/javascript_nodejs/81.skills-skilldialog/dialogRootBot/index.js
> +const conversationIdFactory = new SkillConversationIdFactory(new MemoryStorage());
Same here.

2021-10-06 20:57 UTC, sw-joelmut commented on samples/javascript_nodejs/80.skills-simple-bot-to-bot/simple-root-bot/index.js
> +const conversationIdFactory = new SkillConversationIdFactory(new MemoryStorage());
I created a new instance of the MemoryStorage because if i used the same one will be shared with the conversationState, currently didn't happen but at some point randomly could replace each other states

2021-10-06 20:59 UTC, ceciliaavila approved these changes

2021-10-13 14:39 UTC, MartinLuccanera approved these changes

2021-10-13 15:24 UTC, sw-joelmut commented
Promoted to MS `https://github.com/microsoft/BotBuilder-Samples/pull/3518`

2021-10-13 15:24 UTC, closed without merging