[#3740] Update dotnet samples to target Net 6
southworks/BotBuilder-Samples pull request #392
Opened 2022-05-10 15:44 UTC by erquirogasw

Addresses # 3740
#minor

## Description
This PR updates the BotBuilder samples to target .NET6

## Specific Changes
- Updated the following samples to target .NET6
  - Console-echo
  - Echo-bot
  - Welcome-user
  - Multi-turn-prompt
  - Using-cards
  - Using-adaptive-cards
  - Suggested-actions
  - QnAmaker
  - CustomQABot
  - Core-bot
  - Npl-with-orchestrator
  - Handling-attachments
  - Proactive-messages
  - Multilingual-bot
  - Custom-dialogs
  - Corebot-app-insights
  - Facebook-events
  - Bot-authentication-msgraph
  - Message-reaction
  - Timex-resolution
  - Scaleout
  - Completx-dialog
  - Prompt-users-for-input
  - State-management
  - Teams-auth
  - Inspection
  - CustomQABot-all-features
  - QnAmaker-all-features
  - Teams-messaging-extensions-search
  - Teams-messaging-extensions-action
  - Teams-messaging-extensions-search-auth-config
  - Teams-messaging-extensions-action-preview
  - Teams-task-module
  - Teams-link-unfurling
  - Teams-file-upload
  - Teams-conversation-bot
  - Teams-start-new-thread-in-channel
  - Skills-simple-bot-to-bot
  - Skills-skilldialog
  - Skills-sso-cloudadapter
- README files updated to target .NET6

## Testing

_Successful build_
<img width="396" alt="image (74)" src="https://user-images.githubusercontent.com/64815358/167668296-982a2a6d-652a-457f-afe8-a8aa8247d51c.png">

2022-05-10 16:53 UTC, ceciliaavila requested changes
These are too many files for one PR. After we finish testing the samples, I think we should split the samples into two or three PRs.

2022-05-10 16:53 UTC, ceciliaavila commented on samples/csharp_dotnetcore/01.console-echo/README.md
> +- [.NET Core SDK](https://dotnet.microsoft.com/download) version 6.0
Net 6 is not Core or Framework, just Net 6. If you see the changes I did for the generators, I left this as:
```suggestion
- [.NET SDK](https://dotnet.microsoft.com/download) version 6.0

```

2022-05-12 20:32 UTC, erquirogasw commented
> These are too many files for one PR. After we finish testing the samples, I think we should split the samples into two or three PRs.

Is it ok if I create three PRs part 1, part 2 and part 3?

2022-05-12 20:35 UTC, ceciliaavila commented
> > These are too many files for one PR. After we finish testing the samples, I think we should split the samples into two or three PRs.
> 
> Is it ok if I create three PRs part 1, part 2 and part 3?

We could split the samples following the categories we used for testing. You can have more than one category per PR, depending on the number of files.

2022-05-16 13:08 UTC, closed without merging