[#3740] Update dotnet samples to target Net 6 #392 - Authentication samples
southworks/BotBuilder-Samples pull request #394
Opened 2022-05-13 14:32 UTC by erquirogasw

Addresses # 3740
#minor

## Description
This PR updates the Authentication samples to target .NET6

## Specific Changes
- Updated the following samples to target .NET6
  - Bot-authentication
  - Bot-authentication-msgraph
  - Teams-auth
- README files updated to target .NET6

## Testing
Authentication samples successfully built
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/64815358/168306102-2e1ee664-7822-499e-91c8-84710786a9e7.png">

2022-05-13 17:21 UTC, sw-joelmut requested changes

2022-05-13 17:21 UTC, sw-joelmut commented on samples/csharp_dotnetcore/46.teams-auth/README.md
> +- [.NET SDK](https://dotnet.microsoft.com/download) version 6.0
This bot is already included in the PR https://github.com/southworks/BotBuilder-Samples/pull/396/files#diff-85f929f06830df2afd3359bebeea0b190f11ad45a24486a49d906fb3074ab5d0

2022-05-13 19:25 UTC, erquirogasw commented on samples/csharp_dotnetcore/46.teams-auth/README.md
> +- [.NET SDK](https://dotnet.microsoft.com/download) version 6.0
Fixed. Thank you!

2022-05-13 19:49 UTC, sw-joelmut commented on samples/csharp_dotnetcore/46.teams-auth/README.md
> +- [.NET SDK](https://dotnet.microsoft.com/download) version 6.0
Remove it from the description as well

2022-05-19 14:05 UTC, ceciliaavila approved these changes

2022-05-19 14:43 UTC, ceciliaavila commented
/Promoted 3753

2022-05-19 14:43 UTC, closed without merging