[#9548] CLU and CICD for BotFramework Composer
southworks/BotBuilder-Samples pull request #410
Opened 2023-05-30 13:34 UTC by JhontSouth

#minor

## Proposed Changes
This PR allows the use of the Composer CICD Pipeline Sample with CLU service instead of LUIS.

  - Added the _Composer CICD Pipeline Sample_ for CLU service.
  - Added the _BasicAssistantCLU_ sample.
  
## Testing
The following image shows the deployed bot working as expected.
![image](https://github.com/southworks/BotBuilder-Samples/assets/122501764/37098052-5245-49bd-86b8-7b0c02c56644)

2023-05-30 17:33 UTC, ceciliaavila requested changes

2023-05-30 17:33 UTC, ceciliaavila commented on composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSampleCLU/BasicAssistantCLU/BasicAssistantCLU/BasicAssistantCLU.csproj
> +    <PackageReference Include="Microsoft.Bot.Builder.AI.Luis" Version="4.18.1" />
This reference should be removed.

2023-05-30 17:33 UTC, ceciliaavila commented on composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSampleCLU/BasicAssistantCLU/BasicAssistantCLU/Startup.cs
> +            provider.Mappings[".lu"] = "application/vnd.microsoft.lu";
Is this necessary?

2023-05-30 17:33 UTC, ceciliaavila commented on composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSampleCLU/BasicAssistantCLU/BasicAssistantCLU/dialogs/imported/Microsoft.Bot.Components.HelpAndCancel/CancelDialog/language-understanding/en-us/CancelDialog.en-us.lu
Shouldn't we remove these .lu files?

2023-05-30 17:33 UTC, ceciliaavila commented on composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSampleCLU/BasicAssistantCLU/BasicAssistantCLU/scripts/DeploymentTemplates/function-template-with-preexisting-rg.json
> +      "defaultValue": true
We should remove all LUIS references from the templates.

2023-05-30 17:33 UTC, ceciliaavila commented on composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSampleCLU/BasicAssistantCLU/BasicAssistantCLU/scripts/DeploymentTemplates/function-template-with-preexisting-rg.json
> +      "defaultValue": ""
Same with this.

2023-05-30 17:33 UTC, ceciliaavila commented on composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSampleCLU/BasicAssistantCLU/BasicAssistantCLU/scripts/README.md
> +   | LUIS prediction resource (Cognitive Services) | Optional          |
These should be removed.

2023-05-30 17:33 UTC, ceciliaavila commented on composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSampleCLU/BasicAssistantCLU/BasicAssistantCLU/scripts/provisionComposer.js
Is this file still used in the new pipeline? maybe we can remove it. Or remove the LUIS steps.

2023-05-30 17:33 UTC, ceciliaavila commented on composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSampleCLU/BasicAssistantCLU/BasicAssistantCLU/settings/appsettings.json
> +  },
I think we should remove these settings.

2023-05-30 17:33 UTC, ceciliaavila commented on composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSampleLUIS/BasicAssistant/BasicAssistant/dialogs/imported/Microsoft.Bot.Components.HelpAndCancel/CancelDialog/knowledge-base/en-us/CancelDialog.en-us.qna
> +> Imported: 68b329da9893e34099c7d8ad5cb9c940
Don't remove the last blank line in files, it's a convention.

2023-06-16 18:20 UTC, erquirogasw reviewed
Are the templates found in the scripts folder inside BassicAssistantCLU necessary? Since the original sample didn't have them.

2023-06-26 18:35 UTC, ceciliaavila approved these changes

2023-06-29 20:26 UTC, sw-joelmut approved these changes

2023-06-30 20:12 UTC, ceciliaavila commented
/promoted 3893

2023-06-30 20:12 UTC, closed without merging