[DotNet] Add Bot Authentication Certificate sample bot
southworks/BotBuilder-Samples pull request #415
Opened 2023-10-10 18:23 UTC by JhontSouth

#minor

## Description
This PR adds a new sample for csharp_dotnetcore that shows how to authenticate the Azure bot through Certificate.

## Proposed Changes
  - Added the new sample _**bot-authentication-certificate**_.
  - Added a simple bot conversation to validate the authentication.
  - Added README file with the instructions and information about the sample.

## Testing
This image shows the new _**bot-authentication-certificate**_ sample working.
![image](https://github.com/southworks/BotBuilder-Samples/assets/122501764/c515dc23-1d73-4e92-8c3a-df515e392822)

2023-10-12 13:51 UTC, ceciliaavila requested changes
Please clean the commit history so the WIP commit is not visible.

2023-10-12 13:51 UTC, ceciliaavila commented on samples/csharp_dotnetcore/84.bot-authentication-certificate/Bots/AuthCertificateBot.cs
> +using Microsoft.Extensions.Logging;
Dialogs and Logging are not necessary.

2023-10-12 15:55 UTC, ceciliaavila approved these changes

2023-10-16 13:27 UTC, sw-joelmut approved these changes

2023-10-16 16:10 UTC, JhontSouth commented
Promoted to 3916

2023-10-16 16:10 UTC, closed without merging