[DotNet] Add Bot Authentication SNI sample bot
southworks/BotBuilder-Samples pull request #416
Opened 2023-10-11 18:28 UTC by JhontSouth

#minor 

## Description
This PR adds a new sample for csharp_dotnetcore that shows how to authenticate the Azure bot using the Subject Name/Issuer from MSAL.

## Proposed Changes
  - Added the new sample _**bot-authentication-sni**_.
  - Added a simple bot conversation to validate the authentication.
  - Added README file with the instructions and information about the sample and how to create a SSL/TSL certificate.

## Testing
This image shows the new _**bot-authentication-sni**_ sample working.
![image](https://github.com/southworks/BotBuilder-Samples/assets/122501764/57e3ff74-7a1c-4130-984e-bd42f634a6f8)

2023-10-12 14:02 UTC, ceciliaavila requested changes

2023-10-12 14:02 UTC, ceciliaavila commented on samples/csharp_dotnetcore/85.bot-authentication-sni/Bots/AuthCertificateBot.cs
> +using Microsoft.Extensions.Logging;
Dialogs and Logging are not necessary.

2023-10-12 14:02 UTC, ceciliaavila commented on samples/csharp_dotnetcore/85.bot-authentication-sni/Bots/AuthCertificateBot.cs
Shouldn't this be called AuthSNIBot ?

2023-10-12 14:52 UTC, sw-joelmut approved these changes

2023-10-12 15:22 UTC, JhontSouth commented on samples/csharp_dotnetcore/85.bot-authentication-sni/Bots/AuthCertificateBot.cs
Yes, you're right

2023-10-12 15:38 UTC, ceciliaavila approved these changes

2023-10-16 16:13 UTC, JhontSouth commented
Promoted to 3917

2023-10-16 16:13 UTC, closed without merging