JS - Update samples and ARM templates to support latest Node version
southworks/BotBuilder-Samples pull request #430
Opened 2024-08-22 13:59 UTC by iberlot

Fixes #

## Proposed Changes

  - 
  -
  -

## Testing

2024-08-27 12:48 UTC, sw-joelmut approved these changes

2024-08-29 20:06 UTC, JhontSouth requested changes
There are some templates with 20-LTS and others with 20-LTS.20, are the last ones okay?

2024-08-29 20:06 UTC, JhontSouth commented on samples/javascript_nodejs/85.bot-authentication-sni/deploymentTemplates/linux/deployUseExistResourceGroup/template-BotApp-with-rg.json
> +      "defaultValue": "NODE|20-LTS.20"
There are some templates with 20-LTS and others with 20-LTS.20, are the last ones okay?

2024-08-29 20:19 UTC, ceciliaavila commented on samples/javascript_nodejs/85.bot-authentication-sni/deploymentTemplates/linux/deployUseExistResourceGroup/template-BotApp-with-rg.json
> +      "defaultValue": "NODE|20-LTS.20"
Nice catch! Fixed. Thanks!

2024-08-29 20:20 UTC, ceciliaavila approved these changes

2024-08-29 20:21 UTC, JhontSouth approved these changes

2024-08-29 20:25 UTC, ceciliaavila commented
/promoted 4010

2024-08-29 20:25 UTC, closed without merging