[#4009] Update samples to support latest Node version - TypeScript
southworks/BotBuilder-Samples pull request #431
Opened 2024-08-26 20:11 UTC by ceciliaavila

Addresses # 4009

## Description
This PR updates the ARM templates of the TypeScript samples to use Node 20 as default.

## Proposed Changes
- Updated Node to version 20 in all ARM templates.
- Upgraded the `restify` dependency to version 10.0.0 and the `@types/restify` to 8.5.12.
- Fix error with missing `moment` module in 13.core-bot sample.
- Fix missing 'next' parameter in '/api/messages' handler to comply with new restify's requirements.

## Testing
These images show the resources created in Azure and a bot working after the deployment.
![image](https://github.com/user-attachments/assets/959654d4-5910-4604-b399-27a30ec541e5)

2024-08-26 20:20 UTC, JhontSouth requested changes
I think that the README file would require to change the node version used to test.

![image](https://github.com/user-attachments/assets/a8479ca6-736a-4bd4-bc17-20f1a84a762d)

2024-08-26 20:40 UTC, ceciliaavila commented
> I think that the README file would require to change the node version used to test.
> 
> ![image](https://private-user-images.githubusercontent.com/122501764/361565262-a8479ca6-736a-4bd4-bc17-20f1a84a762d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MDQzMzcsIm5iZiI6MTcyNDcwNDAzNywicGF0aCI6Ii8xMjI1MDE3NjQvMzYxNTY1MjYyLWE4NDc5Y2E2LTczNmEtNGJkNC1iYzE3LTIwZjFhODRhNzYyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQyMDI3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjlkZjRkNzE0YWZlNzVjY2FhYjI5Yzg0M2UxMTIxMGM1YzFmOWNmMTBjZjc5ZjZjOTllMzU0ZWRhNzdlYzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1NrOT_xumg9-J82TLmG2uuayY3DkVyp-QOBcJtpkpsE)

mmm.... yes, maybe we could use node 18 or greater.

2024-08-27 12:43 UTC, JhontSouth approved these changes

2024-08-27 12:48 UTC, sw-joelmut approved these changes

2024-08-29 20:27 UTC, ceciliaavila commented
/promoted 4011

2024-08-29 20:27 UTC, closed without merging