[netcore][13.basic-bot] Fix typos and improve formatting
southworks/BotBuilder-Samples pull request #72
Opened 2018-10-05 19:09 UTC by VictorGrycuk

## Proposed Changes
Fix several typos in sample # 13 and minor text format fixes
## Testing
Code behavior was not modified.

2018-10-08 21:05 UTC, joseques approved these changes

2018-10-10 15:05 UTC, dfavretto requested changes
- [ ] Typo in [BasicBot line 168](https://github.com/southworkscom/BotBuilder-Samples/blob/19f17fdab7c69b9405a516db274c7388ddb74799/samples/csharp_dotnetcore/13.basic-bot/BasicBot.cs#L168)
- [ ] Typo in [BasicBot line 258](https://github.com/southworkscom/BotBuilder-Samples/blob/19f17fdab7c69b9405a516db274c7388ddb74799/samples/csharp_dotnetcore/13.basic-bot/BasicBot.cs#L258)

2018-10-10 15:25 UTC, VictorGrycuk commented
Fixed missing typos

2018-10-10 19:02 UTC, dfavretto approved these changes

2018-10-11 12:56 UTC, dfavretto commented
Closed due to #671

2018-10-11 12:56 UTC, closed without merging