[netcore][15.handling-attachments] Fix typos and improve formatting
southworks/BotBuilder-Samples pull request #79
Opened 2018-10-08 18:44 UTC by VictorGrycuk

## Proposed Changes
Fix several typos in sample # 15 and minor text format fixes
## Testing
Code behavior was not modified.

2018-10-10 19:30 UTC, dfavretto requested changes

2018-10-10 19:30 UTC, dfavretto commented on samples/csharp_dotnetcore/15.handling-attachments/readme.md
>  The types of attachments that may be sent and recieved varies by channel. Additionally, a bot may also recieve file attachments.
Change `recieved` for `received`
Change `recieve` for `receive`

2018-10-10 20:00 UTC, VictorGrycuk commented
Fix additional typos

2018-10-10 20:03 UTC, dfavretto approved these changes

2018-10-12 13:23 UTC, VictorGrycuk commented
Replaced with https://github.com/Microsoft/BotBuilder-Samples/pull/680

2018-10-12 13:23 UTC, closed without merging