[nodejs][01.console echo] Fixed minor typos for README
southworks/BotBuilder-Samples pull request #84
Opened 2018-10-09 14:40 UTC by joseques

## Proposed Changes
- Changed `&` to `&&` since only one ampersand makes the commands run asynchronously thus fail due to `npm start` being executed **before** `npm i` can finish installing the dependencies.

2018-10-09 14:42 UTC, VictorGrycuk approved these changes
LGTM

2018-10-12 20:18 UTC, dfavretto requested changes
[line 42 in file consoleAdapter.js](https://github.com/southworkscom/BotBuilder-Samples/blob/eeeee2e909da45096db9dba78c2cbc8fe67b9260/samples/javascript_nodejs/01.console-echo/consoleAdapter.js#L42) change `activites` for `activities`

2018-10-12 20:21 UTC, joseques commented
Typo fixed @dfavretto

2018-10-12 20:24 UTC, dfavretto approved these changes

2018-10-16 12:20 UTC, dfavretto commented
Closed due to Microsoft#694

2018-10-16 12:20 UTC, closed without merging