[nodejs][03.welcome-users] Fixed wrong .bot filenames
southworks/BotBuilder-Samples pull request #88
Opened 2018-10-09 17:21 UTC by joseques

## Proposed Changes

- Replace `.bot` file names in `index.js` to the correct one.
- Rename `.bot` file to match sample name
- Match casing in README.md with bot filename

2018-10-09 17:36 UTC, VictorGrycuk requested changes
For [Deploy this bot to Azure](https://github.com/southworkscom/BotBuilder-Samples/blob/088536f34efba724bca8f8d70b25f9d8d01ea267/samples/javascript_nodejs/03.welcome-users/README.MD#deploy-this-bot-to-azure), see if  you can replicate the way it is explained [here](https://github.com/southworkscom/BotBuilder-Samples/blob/00d5391cd660b93c35cd9ff1c0211463e7d7b29d/samples/csharp_dotnetcore/17.multilingual-bot/readme.md#deploy-this-bot-to-azure).

2018-10-09 17:40 UTC, joseques commented
Updated PR @VictorGrycuk

2018-10-09 17:44 UTC, VictorGrycuk approved these changes

2018-10-11 13:46 UTC, VictorGrycuk requested changes

2018-10-11 13:46 UTC, VictorGrycuk commented on samples/javascript_nodejs/03.welcome-users/README.MD
> +You can use the [MSBot](https://github.com/microsoft/botbuilder-tools) Bot Builder CLI tool to clone and configure any services this sample depends on. In order to install this and other tools, you c
Please see if you can update this section to the latest one used in [netcore](https://github.com/southworkscom/BotBuilder-Samples/blob/78a021e12898d684f8c48bb72c6c2ca332e62c99/samples/csharp_dotnetcore/13.basic-bot/README.md#deploy-this-bot-to-azure).

2018-10-11 13:52 UTC, VictorGrycuk requested changes
For [line 12](https://github.com/southworkscom/BotBuilder-Samples/pull/88/files#diff-8318bbe5906d2e8faa3e10876f459391R12), use `code formating` for the path.

2018-10-11 14:04 UTC, VictorGrycuk approved these changes

2018-10-11 14:08 UTC, joseques commented
@VictorGrycuk Updated with changes in [line 12](https://github.com/southworkscom/BotBuilder-Samples/pull/88/files#diff-8318bbe5906d2e8faa3e10876f459391R12)

2018-10-16 20:55 UTC, dfavretto requested changes
Fix typo in [line 97](https://github.com/southworkscom/BotBuilder-Samples/blob/d04a523fe3f1dc6504d23016c5b4882bbe6a1d88/samples/javascript_nodejs/03.welcome-users/bot.js#L97) file `bot.js`

2018-10-17 12:42 UTC, joseques commented
Updated @dfavretto

2018-10-17 12:56 UTC, dfavretto approved these changes

2018-10-18 12:50 UTC, dfavretto commented
Closed due to Microsoft#719

2018-10-22 20:11 UTC, joseques commented
Reopened for needed changes. I think the path pointing to an incorrect folder path it's a needed change. @VictorGrycuk @dfavretto

2018-10-25 16:09 UTC, dfavretto commented
Closed due to Microsoft#719

2018-10-25 16:09 UTC, closed without merging